### ISSUE TITLE
Codebase refactoring

### ISSUE THREAD

**Issue by simone3991** [xtreamsrl/clockify-nlp-bot#3]
We need to draft a list of refactoring activities to be acted upon our codebase, with the aim to minimize code smells, maximize extensibility and remove any xtream specific feature

Tasks:
- [x] #22
- [x] #23
- [x] #24
- [x] #25
- [x] #16

**Comment by simone3991** [comment]
To do:

- rewrite `RichClockifyClient` component
- segregate model and DTOs
- possibly rearchitect bot dialogs

**Comment by khaelys** [comment]
#23 and #25 will be rescheduled, so I am closing close this issue.
