### ISSUE TITLE
Remove luis intent enum handling from ClockifyHandler

### ISSUE THREAD

**Issue by khaelys** [xtreamsrl/clockify-nlp-bot#30]
ClockifyHandler handles all intents from Luis, but some of them like "Stop" or "Help" are cross-cutting concerns and should be extracted away.

I propose to introduce domain enums that are a subset of the Luis intent enum and keep everything isolated. 

The only disadvantage is that we don't know at compile time if all Luis intents are handled.

**Comment by simone3991** [comment]
I think we could close this considering the work that has been pushed as part of #51, where cross-cutting intents are now handled by a dedicated component
