### ISSUE TITLE
Avoid redundant and expensive calls to LUIS down the handler chain

### ISSUE THREAD

**Issue by simone3991** [xtreamsrl/clockify-nlp-bot#57]

**Comment by khaelys** [comment]
I initially thought to inject a scoped luis proxy into the IBotHandler(s) but it looks bad as mentioned in [this article](https://samwalpole.com/using-scoped-services-inside-singletons). 

I am going to just update the IBotHandler Handle method signature for now.

**Comment by khaelys** [comment]
I added Luis result in the Handle method parameter, but I am unsure if it won't cover some cases. 
Think about a dialog that need Luis to be selected the first time and in another step that dialog need to contact luis one more time. 

Basically this solution is good only to select the right dialog if there are not active dialogs
