### ISSUE TITLE
Add time zone configuration

### ISSUE THREAD

**Issue by LorenDB** [xtreamsrl/clockify-nlp-bot#74]
I'm noticing that the bot is set to Italy time. For a resident of the United States, this time difference can be a bit jarring when the bot starts asking you to fill in your time for the day while it's still morning. I understand that this might be because the instance that I'm using is hosted in Italy; however, it seems limiting to force users to use a bot hosted in their time zone. Could this be fixed?

**Comment by simone3991** [comment]
Yes it can, true story I was about to open an issue myself since I foresaw this problem.
We can detect the tz from the channel and use it to schedule the reminder

**Comment by simone3991** [comment]
@khaelys after a look at the clockify api [docs](https://clockify.me/developers-api) turns out we can infer this from the user settings there, rather than from the channel. So it is channel-independent and reliable

**Comment by khaelys** [comment]
@LorenDB You should receive the reminders between 17:30 and 23:30 now. If the problem persists, please let me know.

**Comment by LorenDB** [comment]
The reminders are coming through at 11:30 AM EDT for me (instead of 5:30 PM as they are supposed to, right?).

**Comment by khaelys** [comment]
@LorenDB Sorry, I forgot to update your timezone. Basically, the timezone is read from clockify only for new token setups. 

Keep me updated, have a nice weekend.

**Comment by LorenDB** [comment]
OK, now it fires at 8:30 PM. I assume that's good enough for y'all?

**Comment by khaelys** [comment]
It should fire from 5:30 PM, your IANA timezone is America/New_York, right?

**Comment by LorenDB** [comment]
Yes, it is

**Comment by LorenDB** [comment]
It's working now, thanks!
