### ISSUE TITLE
Add InMemoryTokenRepository

### ISSUE THREAD

**Issue by khaelys** [xtreamsrl/clockify-nlp-bot#88]
Currently, clockify tokens are stored in Azure KeyVault using the [TokenRepository](https://github.com/xtreamsrl/clockify-nlp-bot/blob/main/src/Data/TokenRepository.cs), but when you run the bot locally, you need to have a KeyVault configured with Azure Identity authentication.

Add another [ITokenRepository](https://github.com/xtreamsrl/clockify-nlp-bot/blob/main/src/Data/ITokenRepository.cs) called `InMemoryTokenRepository` that will be used when no KeyVaultName env variables is found.

**Comment by kashifsoofi** [comment]
Can I please take this
